app = "planfidence"
primary_region = "iad"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[env]
  FLASK_ENV = "production"
  PORT = "5000"

[[services.ports]]
  handlers = ["http"]
  port = 80
  force_https = true

[[services.ports]]
  handlers = ["tls", "http"]
  port = 443

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
